### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by Sonric** [MarioniLab/CpGisland2017#1]
Hello, Mike!
I want to ask a question. Is the Dropbox folder mentioned in your code uploaded? Because I want to get a data which associated with gene name and CpG islands annotation. But USCS table browser can not do this directly. Maybe your coding can help me to understanding it! Thank you! 
Sonric.

**Comment by MikeDMorgan** [comment]
Hi Sonric,
You can achieve this fairly easily with bedtools (https://bedtools.readthedocs.io/en/latest/). Take the set of gene promoters, however you have defined them, in a BED or GTF file, then use `bedtools intersect` with the CpG island annotation BED file from UCSC.

This will give you the CpG islands that overlap gene promoters - you can even keep the gene names for the promoters in the name field of the BED file.

Best
Mike

**Comment by Sonric** [comment]
Thank you very much for your response, Mike! I will have a try latter.

Best
Sonric

**Comment by MikeDMorgan** [comment]
Great - just re-open this issue if you have any more questions.
